kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: hayd/alpine-deno:1.3.1
    commands:
      - deno cache main.ts
      - deno test

  - name: docker w/ publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pw
      repo: cavejay/dynatrace-drone-events
      tags: latest
      auto_tag: true
      dockerfile: ./dockerfile

  - name: Use Plugin to push event to dt environment
    image: cavejay/dynatrace-drone-events
    settings:
      dynatrace_environment:
        from_secret: dtenv
      dynatrace_api_token:
        from_secret: dttoken
      tagrules:
        - HOST=HyperVisor&&[CONTEXTLESS]SableBeast
      customproperties:
        - msg=This is what I wanted to say
        - msg2=We're just showing the other custom prop values

  - name: Notify
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      message: >
        {{#success build.status}}
          dynatrace-drone-events build {{build.number}} succeeded. Yay.
        {{else}}
          dynatrace-drone-events build {{build.number}} failed. Fix me please.
        {{/success}}
